table Statistiche
	lineageTag: f9afea76-631c-45d2-ac57-35629d95ad0b

	measure SumDistanza = SUM(Statistiche[Distanza])
		formatString: #,0.00
		lineageTag: 711a806d-a1b6-4c4d-aeb8-85471294278b

	measure SumTempo = sum(Statistiche[Tempo])
		formatString: #,##0.#####
		lineageTag: 6e44d2a5-deb1-4ff3-9875-3f1ecc1dd574

		annotation PBI_FormatHint = {"isCustom":true}

	measure SumNrNodi = SUM(Statistiche[NrNodi])
		formatString: 0
		lineageTag: e0e1d756-e2ff-4566-97f5-22a757cfeb89

	column Istanza
		dataType: string
		lineageTag: 5c6a6fd2-3257-44ea-a8a3-ac9ddbcbbc46
		summarizeBy: none
		sourceColumn: Istanza

		annotation SummarizationSetBy = Automatic

	column Algoritmo
		dataType: string
		lineageTag: 654e617c-b080-4590-a414-d98b762ea135
		summarizeBy: none
		sourceColumn: Algoritmo

		annotation SummarizationSetBy = Automatic

	column Distanza
		dataType: double
		formatString: 0.00
		lineageTag: 7e04acdb-7fb3-4742-b627-d6923c36185e
		summarizeBy: sum
		sourceColumn: Distanza

		annotation SummarizationSetBy = Automatic

	column Tempo
		dataType: double
		formatString: 0.00000
		lineageTag: 9b72068c-f185-4313-9556-c92a87966913
		summarizeBy: sum
		sourceColumn: Tempo

		annotation SummarizationSetBy = Automatic

	column NrNodi
		dataType: int64
		formatString: 0
		lineageTag: 43ec1c6b-c83d-471b-8b8f-a73153cf5195
		summarizeBy: sum
		sourceColumn: NrNodi

		annotation SummarizationSetBy = Automatic

	partition Statistiche = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\t.rivieccio\Desktop\Algoritmi-di-Ottimizzazione-Combinatoria-e-su-Rete-\Statistiche PBI\statistiche.xlsx"), null, true),
				    Tabella1_Table = Origine{[Item="Tabella1",Kind="Table"]}[Data],
				    #"Modificato tipo" = Table.TransformColumnTypes(Tabella1_Table,{{"Istanza", type text}, {"Algoritmo", type text}, {"Distanza", type number}, {"Tempo", type number}, {"NrNodi", Int64.Type}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione

